let episodesTitle=("le premier voyage");
let épisodeDuration=45;
let hasBeenwatched=true;
let type_de_donnees=document.getElementById('type_de_donnees');
type_de_donnees.innerText ='"le titre":${episodesTitle}, "duration":${épisodeDuration}"minutes", "est_ce_que vous avez vu l\'pisode?":${hasBeenwatched} "oui"';

////une autrefacçon d'ecrire les operations

/*let numberOfCats = 2;

numberOfCats *= 6;  // numberOfCats vaut maintenant 2*6 = 12; 

numberOfCats /= 3;  // numberOfCats vaut maintenant 12/3 = 4;*/